name: charm_android_app
description: Local DnD character sheet app inspired by Charm UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
